name : DevDroids
brand : DevDroids
description : DevDroids is all about android development
keyword : android, development, programming, android sdk
url : http://devdroids.com
email : info@pragmaticself.com
twitter : alpargabos
github : alpargabos
author : Alpar Gabos
analytics : UA-65345359-3
year : 2016
markdown : kramdown
exclude : ["node_modules", "gulpfile.js", "package.json"]
paginate: 9
paginate_path: "/page:num/"
